
assertThatThrownBy(() -> shouldThrow()); // Noncompliant, is it really the exception you expected?
